name: Bonus Tests
on: [push]
jobs:
  bonus_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minunit
    steps:
    - uses: actions/checkout@v2
    - name: Bonus Tests
      run: make bonus