name: Extra Tests
on: [push]
jobs:
  extra_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minunit
    steps:
    - uses: actions/checkout@v2
    - name: Extra Tests
      run: make e