name: Mandatory Tests
on: [push]
jobs:
  mandatory_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minunit
    steps:
    - uses: actions/checkout@v2
    - name: Mandatory Tests
      run: make